### ISSUE TITLE
EFS

### ISSUE THREAD

**Issue by kikobr82** [devopsacademyau/2020-jun-project1-group2#3]
**Objectives:**
- Use vpc from network stack
- Available in both AZs
- Security group allowing only ECS instances to access it
- No lifecycle policy
- Throughput mode bursting
- Performance mode general purpose
- No need for encryption
- No need for IAM authentication
- Add one access point:
- Name wordpress
- Path `/wordpress`

**Acceptance Criteria:**
- EFS is available in at least two AZ
- I can mount efs volume on an ec2 instance running on private subnet following instructions https://docs.aws.amazon.com/efs/latest/ug/mounting-fs.html
- I CAN'T mount efs volume from instance on public subnet

**Comment by mrcsmonteiro** [comment]
- Public & private instances:

![image](https://user-images.githubusercontent.com/30852082/89128916-4a541580-d53c-11ea-98e4-3b698283f6de.png)

- EFS is available in at least two AZ:

![image](https://user-images.githubusercontent.com/30852082/89128645-6c4c9880-d53a-11ea-9feb-c327fe12ee68.png)

- I can mount efs volume on an ec2 instance running on private subnet

![image](https://user-images.githubusercontent.com/30852082/89128865-ef222300-d53b-11ea-9091-49c37f10802c.png)

- I CAN'T mount efs volume from instance on public subnet

![image](https://user-images.githubusercontent.com/30852082/89128713-014f9180-d53b-11ea-9c8e-e69f33998237.png)
