### ISSUE TITLE
ECS Cluster

### ISSUE THREAD

**Issue by kikobr82** [devopsacademyau/2020-jun-project1-group2#4]
**Objectives:**
- Create a ECS Cluster
- Cluster can be using Fargate or EC2 Instances
- The cluster is high available across 2 AZs
- Hosted in private Zone
- Security Groups are created with least privileges
- IAM roles required are associated with the cluster nodes

**Acceptance Criteria:**
- ECS cluster is visible from the AWS console
- There is no SG with 0.0.0.0/0
- The cluster can pull images from ECR
- Documentation is updated with information related t the ECS cluster

**Comment by mrcsmonteiro** [comment]
- ECS cluster is visible from the AWS console

![image](https://user-images.githubusercontent.com/30852082/89131335-6319f680-d54f-11ea-86e4-cbbfc3532106.png)

- There is no SG with 0.0.0.0/0

![image](https://user-images.githubusercontent.com/30852082/89131708-4501c580-d552-11ea-8434-955804bb3778.png)
![image](https://user-images.githubusercontent.com/30852082/89131711-4f23c400-d552-11ea-8cab-efcf29857e7c.png)

- The cluster can pull images from ECR

![image](https://user-images.githubusercontent.com/30852082/89132738-aa0ce980-d559-11ea-8add-089f595be660.png)
![image](https://user-images.githubusercontent.com/30852082/89132751-c1e46d80-d559-11ea-88d5-efe620e93796.png)

- Documentation is updated with information related t the ECS cluster

TO DO
